version: "3"

services:
  postgres:
    build: ./docker/postgres
    image: heart_postgres
    container_name: heart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heart
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432

  pgadmin:
    build: ./docker/pgadmin
    image: heart_pgadmin
    container_name: heart_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 8080:80

  node:
    build: ./docker/node
    image: heart_node
    container_name: heart_node
    depends_on:
      - "postgres"
    volumes:
      - ./app:/code
    ports:
      - 3000:3000
